name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Synchronize npm lock file
        run: |
          npm install
          npm install -g npm@latest

      - name: Add AWS VM's host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts


      - name: Copy code to AWS VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /home/${{ secrets.USERNAME }}/prod/frontend

      # - name: Copy env
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
      #     chmod 600 private-key.pem
      #     ssh -i private-key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} -o StrictHostKeyChecking=no << 'ENDSSH'
      #       cd /home/${{ secrets.USERNAME }}/prod/frontend
      #       touch .env.local
      #       cp /home/${{ secrets.USERNAME }}/env/prod/frontend/.env.local ./.env.local
      #     ENDSSH

      - name: Build and run Docker image on AWS VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          ssh -i private-key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} -o StrictHostKeyChecking=no << 'ENDSSH'
            cd /home/${{ secrets.USERNAME }}/prod/frontend
            sudo systemctl stop prod-frontend || true  
            docker build --no-cache -t prod-frontend .
            docker images -a
            
            # Remove the old container if it exists
            docker rm -f my-prod-frontend || true
            
            # Run the new Docker container
            docker run --name my-prod-frontend -d -p 5000:5173 prod-frontend:latest 
            
            docker ps -a
            echo "Prod deployment complete"
          ENDSSH
